# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"NumericalizePair": "00_data.ipynb",
         "Pad_Chunk_Pair": "00_data.ipynb",
         "Undict": "00_data.ipynb",
         "load_dataset": "00_data.ipynb"}

modules = ["data.py"]

doc_url = "https://numb3r33.github.io/matchpyramid/"

git_url = "https://github.com/numb3r33/matchpyramid/tree/main/"

def custom_doc_links(name): return None
